FROM node:20-alpine

WORKDIR /app

COPY apps/gateway/package.json ./
RUN npm install --production

COPY apps/gateway/server ./server
COPY apps/gateway/client ./client

EXPOSE 3005

CMD ["node", "server/index.js"]
